export const ADD_PRODUCT_REQUEST="ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL="ADD_PRODUCT_FAIL"
export const ADD_PRODUCT_RESET="ADD_PRODUCT_RESET"

export const VIEW_PRODUCT_REQUEST="VIEW_PRODUCT_REQUEST"
export const VIEW_PRODUCT_SUCCESS="VIEW_PRODUCT_SUCCESS"
export const VIEW_PRODUCT_FAIL="VIEW_PRODUCT_FAIL"
export const VIEW_PRODUCT_RESET="VIEW_PRODUCT_RESET"


export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET="DELETE_PRODUCT_RESET"